name: shpc update docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

  push:
    branches: [main]


jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "gh-pages"

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name shpc spython

      - name: Install shpc
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          pip install git+https://github.com/singularityhub/singularity-hpc@main
          git clone https://github.com/singularityhub/shpc-registry /tmp/registry

      - name: Generate docs
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          /bin/bash generate.sh /tmp/registry

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .
